# in thi file you can specify the hosts and the connection type
local: # name of the group of hosts
  hosts: # list of hosts
    localhost: # name of the host in the group for which the playbook will be executed
      ansible_connection: local # connection type to the host
      ansible_become: yes
      ansible_become_password: "{{ vault_ansible_become_pass }}"